$bamMgmt = New-WebServiceProxy -Uri "http://pifbti01.leeds.gov.uk/BAM/BAMManagementService/BAMManagementService.asmx" -UseDefaultCredential
$bamQuery = New-WebServiceProxy -Uri "http://pifbti01.leeds.gov.uk/BAM/BAMQueryService/BamQueryService.asmx" -UseDefaultCredential
$bamQuery.GetIn

function Get-InstanceData {
    [CmdletBinding()]
    param (
        [Parameter(Position = 0, Mandatory = $true, ValueFromPipeline = $true)]
        [string]$View,
        [Parameter(Position = 1, Mandatory = $true)]
        [string]$Activity,
        [Parameter(Mandatory = $true)]
        [string[]]$Columns,
        [Parameter()]
        [int]$Timeout = 15
    )
    process {
        $query = [Microsoft.PowerShell.Commands.NewWebserviceProxy.AutogeneratedTypes.WebServiceProxy3ryService_BamQueryService_asmx.InstanceQuery]::new()
        $query.SelectClauses = $Columns

        return $bamQuery.GetInstanceData($View, $Activity, $query, $Timeout)
    }
}

function Get-ViewDetails {
    [CmdletBinding()]
    param (
        [Parameter(Position = 0, Mandatory = $true, ValueFromPipeline = $true)]
        [string]$View
    )
    begin {
        $viewName = @{Name="View";Expression={$_.View.Name}}
        $activityName = @{Name="Activity";Expression={$_.View.ActivityView.Name}}
        $columns = @{Name="Columns";Expression={$_.View.ActivityView.Alias.Name}}
    }
    process {
        $xml = [xml]$bamMgmt.GetViewDetailsAsXml($View)
        return $xml.BAMDefinition | Select-Object -Property $viewName,$activityName,$columns
    }
}

function Get-ViewsSummary {
    [CmdletBinding()]
    param ()
    process {
        return $bamMgmt.GetViewSummaryForCurrentUser().View
    }
}